/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "M2_PWM.h"
#include "MOT_IN1.h"
#include "MOT_IN1_aliases.h"
#include "Clock_pwm.h"
#include "M1_PWM.h"
#include "encA.h"
#include "encA_aliases.h"
#include "encB.h"
#include "encB_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "ENC.h"
#include "ADC_Sensing.h"
#include "ADC_Configuration.h"
#include "ADC_Adc.h"
#include "ADC_Structure.h"
#include "TX_EN.h"
#include "TX_EN_aliases.h"
#include "LED_ACT.h"
#include "LED_ACT_aliases.h"
#include "MOT_IN2.h"
#include "MOT_IN2_aliases.h"
#include "M1_ISR.h"
#include "M2_ISR.h"
#include "Clock_ENC.h"
#include "SYSTCK_TIMER.h"
#include "SYSTCK_ISR.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_SCB_IRQ.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "ADC_ISR.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

